<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategory($id)
    {
        $query = $this->createQueryBuilder('articles')
            ->select('articles')
            ->leftJoin('articles.categories', 'categories')
            ->addSelect('categories');

        $query = $query->add('where', $query->expr()->in('categories.id', ':id'))
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();

        return $query;
    }
}
